### ISSUE TITLE
Dynamic field set form widget

### ISSUE THREAD

**Issue by khoatran** [kleverbee/octobercms-blueprint#1]
### Use case 1
Assume that we're developing a plugin called Portfolio. Inside this Portfolio plugin, we created a model: Portfolio. The standard portfolio model contains: name, description, image, photo_galleries. 
However, when we put this plugin to a new business context - let's say: Real estate, there are more fields that we want to put into it: investor, constructor ...

So, how do we reach that goal?
Normally, there are 2 ways to do that. 
 - The most popular way is:  extending the model in the boot method of the new plugin.
 - The second way is using the dynamic field. By this way, in the Portfolio plugin, we add a field, eg: extended_fields and configure it to point to a field set code.
 
 The example code for the extended field is as below:
 ```
 custom_fields:  
    label: Custom field  
    type: dynamic_field  
    fieldSetCode: 'portfolio-fieldset'
 ```

 So, when we put this plugin to a new context. We only need to create and configure the field set 'portfolio-fiel
